### ISSUE TITLE
R3 and R2 smarthealthit.org servers appear to be down

### ISSUE THREAD

**Issue by bryantaustin13** [AHRQ-CDS/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY#11]
(This  might be completely the wrong place to post this.  If so, please excuse me and let me know where/who to contact.)

When attempting to browse patients for the R2 and R3 servers a Bad Gateway error occurs"
http://patient-browser.smarthealthit.org/index.html?_=1587049045747&config=r2#/
http://patient-browser.smarthealthit.org/index.html?_=1587049244586&config=r3#/

Error: certificate has expired - Bad Gateway

When attempting to access the servers from Postman
GET https://r3.smarthealthit.org
returns 
There was an error connecting to https://r3.smarthealthit.org/.

Do we have an estimated time for them to be back up?

Thanks!

**Comment by cmoesel** [comment]
This seems to be related to the SMART Health IT gallery and sandbox.  We have no control over that.  I'd recommend that you go over to https://apps.smarthealthit.org/, scroll down to the bottom, and click the "Contact Us" link.

**Comment by bryantaustin13** [comment]
Thanks!
    On Thursday, April 16, 2020, 09:46:42 AM MDT, Chris Moesel <notifications@github.com> wrote:  
 
 


This seems to be related to the SMART Health IT gallery and sandbox. We have no control over that. I'd recommend that you go over to https://apps.smarthealthit.org/, scroll down to the bottom, and click the "Contact Us" link.
