### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by brynrhodes** [AHRQ-CDS/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY#12]
I've taken a fresh clone and tried to run and am getting the following error:

`Cannot add launch.js to entry. Unexpected starting value for entry: [`

Which appears to be coming from this line in the .rescriptsrc.js:
https://github.com/AHRQ-CDS/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY/blob/master/.rescriptsrc.js#L25

Before I dig too much further on this, can you confirm whether being able to run on Windows is expected to work?

**Comment by cmoesel** [comment]
We _expect_ it to work in Windows, but we have not recently tested it in Windows.  I believe others who use Windows have had success.  I just tested a clean clone on my Mac to make sure there isn't some larger issue at play.  Unfortunately, I don't have a Windows machine easily available to me right now...

A few things to check:
* Are you using Node 0.12.x?
* Is your yarn up to date?
* Did you use `yarn` to install the dependencies?  (using `npm` is untested).

**Comment by mcjustin** [comment]
We made changes in our branch to address this, see https://github.com/uwcirg/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY/commit/9ef1881ee4227cd10aa32fe123096bfdf56e4643 . Checking w/ others here to see whether any of that commit introduces dependencies novel to our branch...

**Comment by mcjustin** [comment]
@achen2401 says that these changes don't add dependencies that are novel to our branch. @ivan-c fyi

**Comment by cmoesel** [comment]
Thanks @mcjustin...  Looking through that commit, however, I'm having trouble seeing what would affect that error with `.rescriptsrc.js`...  Most of the changes you applied seem like they would happen well after rescript has been executed.  Do you know which specific bit addressed the issue Bryn is asking about?

**Comment by achen2401** [comment]
@cmoesel  At least for us, the error was specific to launch.js so polyfills are imported specifically in that file and the error went away after that for us.  I don't know if that is the same issue that Bryan is experiencing.
![Screen Shot 2020-05-29 at 10 59 29 AM](https://user-images.githubusercontent.com/12942714/83290530-9a5cd780-a19b-11ea-9ca8-fcee52295ea5.png)

**Comment by brynrhodes** [comment]
Ah yes, I'm not getting to that point, the error is preventing the launch entry from being added. And I confirmed by taking a local clone of the referenced branch and I still get the "Could not add launch entry" error.

I also note that I got this from building on that fork:
```
  `@babel/polyfill` is deprecated. Please, use required parts of `core-js`
  and `regenerator-runtime/runtime` separately
```
Not sure if that's a known issue, but wanted to note it in case it's helpful.

**Comment by brynrhodes** [comment]
And @cmoesel , thank you for the suggestions, I verified my node is v12.14.1, and I didn't have yarn yet, so that was a fresh install of latest, and I did use yarn to install the dependencies locally.

**Comment by achen2401** [comment]
> 
> I also note that I got this from building on that fork:
> 
> ```
>   `@babel/polyfill` is deprecated. Please, use required parts of `core-js`
>   and `regenerator-runtime/runtime` separately
> ```
> 
> Not sure if that's a known issue, but wanted to note it in case it's helpful.

Thanks @brynrhodes I will make the necessary fixes.

**Comment by cmoesel** [comment]
@brynrhodes -- what is the full error you got?  You posted only the first line, but I expect there is more to it?

Another thing I've seen before is strangeness related to what shell you are using.  I think on Windows there are a few choices.  Maybe try it in a different shell?

Most of us on my team have Mac.  The one guy who has Windows is on vacation this week! :-/

**Comment by brynrhodes** [comment]
@cmoesel , here's the full log
```
yarn run v1.22.4
$ rescripts start
Cannot add launch.js to entry. Unexpected starting value for entry: [
  'C:\\Users\\Bryn\\Documents\\Src\\AHRQ\\AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY\\node_modules\\react-dev-utils\\webpackHotDevClient.js',
  'C:\\Users\\Bryn\\Documents\\Src\\AHRQ\\AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY\\src\\index.js'
]
i ｢wds｣: Project is running at http://10.0.75.1/
i ｢wds｣: webpack output is served from
i ｢wds｣: Content not from webpack is served from C:\Users\Bryn\Documents\Src\AHRQ\AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY\public
i ｢wds｣: 404s will fallback to /
```

**Comment by brynrhodes** [comment]
I'm using the default command shell, I'll try with powershell...

**Comment by brynrhodes** [comment]
FYI, running in powershell gave exactly the same output

**Comment by cmoesel** [comment]
Oh.  That full error definitely helps.  It looks like an issue w/ file separators (Windows vs Mac).  I don't know how this hasn't been an issue before unless something happened that changed how the contents of that array are represented.  Anyway, I think I can fix that.  Standby and I'll try to have a branch ready in the next 30 minutes or so.

**Comment by cmoesel** [comment]
@brynrhodes -- can you try the [fix-rescript-windows](https://github.com/AHRQ-CDS/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY/tree/fix-rescript-windows) branch to see if it fixes the issue?

**Comment by brynrhodes** [comment]
@cmoesel , thank you so much, different output, at this point:
```
yarn run v1.22.4
$ rescripts start
Cannot modify output filename. Unexpected starting value: static/js/bundle.js
i ｢wds｣: Project is running at http://10.0.75.1/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\Users\Bryn\Documents\Src\AHRQ\AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY\public
i ｢wds｣: 404s will fallback to /index.html
Starting the development server...

Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`

  `@babel/polyfill` is deprecated. Please, use required parts of `core-js`
  and `regenerator-runtime/runtime` separately
```
Not sure whether that "cannot modify output file name" is relevant?

**Comment by brynrhodes** [comment]
It definitely gets further, I'm able to pick the patient, but it stalls there:
![image](https://user-images.githubusercontent.com/6983498/83299915-4d392f80-a1b4-11ea-8eba-082b732f632b.png)

**Comment by cmoesel** [comment]
Well that's annoying.  Apparently React uses OS-specific path separators in some places and not in others.  I was over-agressive in my application of OS-specific path separators.  And I think that the blank screen is probably related to that error.  I'm less concerned about caniuse-lite and @babel/polyfill right now.

I just pushed a new commit that I think will fix the issue for you.  If I new the emoji code for crossed fingers, I would use it right now.

**Comment by brynrhodes** [comment]
You, sir, are a wizard! Totally worked:
![image](https://user-images.githubusercontent.com/6983498/83302873-4e209000-a1b9-11ea-9a64-440b55fb7244.png)

(ninja)
Thank you so much!

**Comment by cmoesel** [comment]
Finally.  ;-)

I just uploaded our test R4 patient.  Her name is Brenda Jackson.  Here is a launch URL (for localhost:8000) that should work for you if you want to try it with Brenda: http://launch.smarthealthit.org/?auth_error=&fhir_version_1=r2&fhir_version_2=r4&iss=&launch_ehr=1&launch_url=http%3A%2F%2Flocalhost%3A8000%2Flaunch.html&patient=5c41cecf-cf81-434f-9da7-e24e5a99dbc2&prov_skip_auth=1&provider=&pt_skip_auth=1&public_key=&sb=&sde=&sim_ehr=1&token_lifetime=15&user_pt=

**Comment by cmoesel** [comment]
Note that the DB resets at midnight, so tomorrow Brenda will (sadly) be gone.  But the DSTU2 version of Brenda is always available, so there's that. (You can search for her by name).

You can also run `yarn upload-test-patients` from the root folder of this app and it will attempt to re-upload R4 Brenda (and other DSTU2 people) -- but it's not always successful due to some strangeness with how the SMART server handles HTTP PUT.

**Comment by brynrhodes** [comment]
Yes, that worked as expected, thank you!

The only question I have now is we are forked off of master; what is the timeline for this fix to be committed to the master branch?

**Comment by cmoesel** [comment]
I don't like to merge without a code review.  How about I get a code review on Monday and merge it in Monday as well.  Does that work for you?

**Comment by brynrhodes** [comment]
Yes, absolutely, I'm just trying to get a sense for whether there's a release cycle (which would be fine, it would just mean we'd need to cherry pick the fix).

**Comment by cmoesel** [comment]
No release cycle.  At this point, we (AHRQ/MITRE) are only doing releases on an as-needed basis.

**Comment by cmoesel** [comment]
@brynrhodes -- this fix is in master now.  Let me know if you run into any issues.
