### ISSUE TITLE
Requires "text" on clinicalStatus

### ISSUE THREAD

**Issue by drdavec** [AHRQ-CDS/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY#6]
There appears to be a bug in the query for Condition.  If the "text" element is omitted, then the Condition will not be reported in the app.  Verified with below from Brenda Jackson in R4, if you remove "text" element.  The same may be true for verificationStatus, but did not check that explicitly.

        "clinicalStatus": {
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
              "code": "active",
              "display": "Active"
            }
          ],
          "text": "Active"
        },

**Comment by cmoesel** [comment]
I agree, the absence of the `text` property should not make any difference to the logic.  We'll look into this issue.  Thanks for reporting it.

**Comment by cmoesel** [comment]
Hello @drdavec -- we've found and fixed the bug.  Without going into too much detail, there was a change from CQL 1.2 to CQL 1.3 that affected how items are matched against a list.  The CDS Connect Commons library for FHIR R4 contained logic that checked the Condition clinical status against a list of concepts.  While this worked with CQL 1.2 implementations, it did not work with CQL 1.3 implementations.  We updated the CDS Connect Commons logic to use an approach that works in all versions of CQL -- ans consequently, in the Pain Management Summary.

This change was pushed to the _master_ branch along with a set of other terminology-related changes and released as version 0.3.0 of the app.  You can see a description of all the changes in the [Pain Management Summary 0.3.0 release notes](https://github.com/AHRQ-CDS/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY/releases/tag/v0.3.0).

Thanks again for reporting this and please let us know if you run into any other issues like it.

**Comment by drdavec** [comment]
Hi Chris,
Thanks very much for your quick response!  I'll test this update and other
improvements tomorrow.

Dave
