### ISSUE TITLE
Unnecessary function?

### ISSUE THREAD

**Issue by maggiedorr** [AHRQ-CDS/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY#7]
https://github.com/AHRQ-CDS/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY/blob/1af209460101262c8016b9138b04aa35a3b599f2/src/cql/r4/Factors_to_Consider_in_Managing_Chronic_Pain_FHIRv400.cql#L961

Why is this function defined here when it was already defined in C3F and used throughout (including directly below)?

**Comment by cmoesel** [comment]
Funny -- I just found that myself yesterday when I was preparing a more detailed change log for the CDS Connect Repository.  I originally put it in there when I was debugging an issue with the C3F library -- and after I didn't need it anymore, I missed taking it out.  I'll remove it.  I also found one minor issue in CDS Connect Commons (R4) that I'll also be addressing.

**Comment by cmoesel** [comment]
This has been fixed in master for a while now, so I'm closing this issue.
